services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest #https://hevodata.com/learn/pgadmin-docker/#s2
    #network_mode: host
    networks:
      - pg_admin_network
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5439:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  pg_admin_network:
    driver: bridge

volumes:
  pgadmin-data:
    driver: local
