// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://omni-connect.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://omni-connect.com/support",
            "email": "support@omni-connect.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/external/v1/charge/dob": {
            "post": {
                "description": "Implements /api/external/v1/{realm}/charge/dob/{partnerRole}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PartnerDobCharging"
                ],
                "summary": "Request Direct Billing charge to TIMWE Partner MA Platform",
                "parameters": [
                    {
                        "description": "Charging request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ChargeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ChargeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/external/v1/subscription/optin/confirm": {
            "post": {
                "description": "Implements /api/external/v1/{realm}/subscription/optin/confirm/{partnerRole}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PartnerOptinConfirm"
                ],
                "summary": "Confirm double opt-in via TIMWE Partner MA Platform",
                "parameters": [
                    {
                        "description": "Confirmation request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SubscriptionConfirmationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/external/v1/subscription/optout": {
            "post": {
                "description": "Implements /api/external/v1/subscription/optout/{partnerRole}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PartnerOptout"
                ],
                "summary": "Unsubscribe user via TIMWE Partner MA Platform",
                "parameters": [
                    {
                        "description": "Unsubscription request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UnsubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/external/v1/subscription/status": {
            "post": {
                "description": "Implements /api/external/v1/{realm}/subscription/status/{partnerRole}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PartnerStatus"
                ],
                "summary": "Get subscription status from TIMWE Partner MA Platform",
                "parameters": [
                    {
                        "description": "Status request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/external/v1/{channel}/mt": {
            "post": {
                "description": "Implements /api/external/v1/{realm}/{channel}/mt/{partnerRole}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PartnerMt"
                ],
                "summary": "Send MT to TIMWE Partner MA Platform",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (SMS/WEB/IVR/USSD)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "MT request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.partnerMtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/churn-candidates": {
            "get": {
                "description": "Returns subscriptions that are candidates for churn based on policy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Monitoring"
                ],
                "summary": "Get churn candidates",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum number of candidates to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Churn candidates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SubscriptionWithRenewalInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to get churn candidates",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/cycles": {
            "get": {
                "description": "Returns renewal cycles with optional filtering by status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Monitoring"
                ],
                "summary": "Get renewal cycles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum number of cycles to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Renewal cycles",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.RenewalCycle"
                            }
                        }
                    },
                    "501": {
                        "description": "Method not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/force-churn-evaluation": {
            "post": {
                "description": "Forces a churn evaluation for all subscriptions based on policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Operations"
                ],
                "summary": "Force churn evaluation",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1000,
                        "description": "Maximum number of subscriptions to evaluate (default: 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Churn evaluation completed",
                        "schema": {
                            "$ref": "#/definitions/handler.ChurnEvaluationResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to evaluate churn candidates",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/health": {
            "get": {
                "description": "Returns the health status of the renewal system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Monitoring"
                ],
                "summary": "Get renewal system health",
                "responses": {
                    "200": {
                        "description": "System health status",
                        "schema": {
                            "$ref": "#/definitions/handler.RenewalHealthResponse"
                        }
                    },
                    "503": {
                        "description": "Worker not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/manual": {
            "post": {
                "description": "Triggers a manual renewal for a specific subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Operations"
                ],
                "summary": "Manual renewal",
                "parameters": [
                    {
                        "description": "Renewal request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ManualRenewalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Renewal response",
                        "schema": {
                            "$ref": "#/definitions/domain.RenewalResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to process renewal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/priority-retry": {
            "get": {
                "description": "Returns items currently in the priority retry queue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Monitoring"
                ],
                "summary": "Get priority retry queue",
                "responses": {
                    "200": {
                        "description": "Priority retry queue items",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PriorityRetryQueue"
                            }
                        }
                    },
                    "501": {
                        "description": "Method not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/priority-retry/process": {
            "post": {
                "description": "Processes the priority retry queue for failed opt-ins",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Operations"
                ],
                "summary": "Process priority retry queue",
                "responses": {
                    "200": {
                        "description": "Queue processed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to process queue",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Worker not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/statistics": {
            "get": {
                "description": "Returns renewal statistics for the specified number of days",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Monitoring"
                ],
                "summary": "Get renewal statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Number of days to look back (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Renewal statistics",
                        "schema": {
                            "$ref": "#/definitions/domain.RenewalMetrics"
                        }
                    },
                    "500": {
                        "description": "Failed to get statistics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/worker/start": {
            "post": {
                "description": "Starts the automated renewal worker that processes subscription renewals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Worker"
                ],
                "summary": "Start renewal worker",
                "responses": {
                    "200": {
                        "description": "Worker started successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Worker already running",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to start worker",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Worker not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/worker/status": {
            "get": {
                "description": "Returns the current status and metrics of the renewal worker",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Worker"
                ],
                "summary": "Get renewal worker status",
                "responses": {
                    "200": {
                        "description": "Worker status and metrics",
                        "schema": {
                            "$ref": "#/definitions/handler.RenewalWorkerStatus"
                        }
                    },
                    "503": {
                        "description": "Worker not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/renewal/worker/stop": {
            "post": {
                "description": "Stops the automated renewal worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renewal Worker"
                ],
                "summary": "Stop renewal worker",
                "responses": {
                    "200": {
                        "description": "Worker stopped successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Worker not running",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to stop worker",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Worker not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external": {
            "post": {
                "description": "Opt-in a user subscription with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Opt-in a single subscription",
                "parameters": [
                    {
                        "description": "Optin Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.OptinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "200",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid\\t query parameters",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/subscription-external/backfill": {
            "post": {
                "description": "If msisdns not provided, finds active MSISDNs missing the provided product_ids and enqueues opt-in jobs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Backfill subscriptions for MSISDNs missing specified products (async)",
                "parameters": [
                    {
                        "description": "Backfill Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BackfillRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted with jobId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/batch": {
            "post": {
                "description": "Enqueue a batch job and return jobId to poll status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Batch Opt-in subscriptions (async)",
                "parameters": [
                    {
                        "description": "Batch Optin Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BatchOptinRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted with jobId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or error generating MSISDNS",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/charging-failures": {
            "get": {
                "description": "Get subscriptions with charging failures using notifications-based analysis with filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargingFailures"
                ],
                "summary": "Get charging failed subscriptions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of results to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by days since last charge notification (default: 30)",
                        "name": "days_threshold",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by subscription status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by charging health status",
                        "name": "health_status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Charging failures retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/charging-failures/stats": {
            "get": {
                "description": "Get comprehensive statistics about charging failures including counts, rates, and trends",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargingFailures"
                ],
                "summary": "Get charging failure statistics",
                "responses": {
                    "200": {
                        "description": "Charging failure statistics retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/charging-failures/summary": {
            "get": {
                "description": "Get a categorized summary of charging failures by health status and failure reasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargingFailures"
                ],
                "summary": "Get charging failure summary",
                "responses": {
                    "200": {
                        "description": "Charging failure summary retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/alerts": {
            "get": {
                "description": "Get current monitoring alerts with optional filtering by severity, type, and acknowledgment status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Get monitoring alerts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by alert severity (low, medium, high, critical)",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by alert type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by acknowledgment status",
                        "name": "acknowledged",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alerts retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/alerts/acknowledge": {
            "post": {
                "description": "Mark a monitoring alert as acknowledged by the specified user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Acknowledge monitoring alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the alert to acknowledge",
                        "name": "alert_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Identifier of who acknowledged the alert",
                        "name": "acknowledged_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional notes about the acknowledgment",
                        "name": "notes",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert acknowledged successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - missing alert_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/alerts/clear": {
            "post": {
                "description": "Remove old acknowledged alerts older than the specified hours",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Clear monitoring alerts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hours threshold for clearing alerts (default: 24)",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alerts cleared successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/dashboard": {
            "get": {
                "description": "Get comprehensive monitoring dashboard data including metrics, alerts, and charts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Get monitoring dashboard data",
                "responses": {
                    "200": {
                        "description": "Dashboard data retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/health": {
            "get": {
                "description": "Get comprehensive health status including system health, alerts, and metrics freshness",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Get monitoring system health status",
                "responses": {
                    "200": {
                        "description": "Health check completed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/metrics": {
            "get": {
                "description": "Get current monitoring metrics for charging failures and system health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Get monitoring metrics",
                "responses": {
                    "200": {
                        "description": "Metrics retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/monitoring/thresholds": {
            "put": {
                "description": "Update the alert thresholds for charging failures",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Update monitoring alert thresholds",
                "parameters": [
                    {
                        "description": "New alert thresholds",
                        "name": "thresholds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/monitoring.AlertThresholds"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thresholds updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid threshold data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/resubscribe": {
            "post": {
                "description": "If msisdns not provided, finds active MSISDNs WITH the provided product_ids using windowing and performs unsubscribe then opt-in again.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Unsubscribe then subscribe again for targeted MSISDNs (async)",
                "parameters": [
                    {
                        "description": "Resubscribe Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BackfillRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted with jobId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/resubscribe/enhanced": {
            "post": {
                "description": "Handles charging-failed subscriptions with comprehensive tracking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Enhanced resubscribe handler with tracking and recovery",
                "parameters": [
                    {
                        "description": "Enhanced Resubscribe Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EnhancedBackfillRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted with jobId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/config": {
            "get": {
                "description": "Get the current configuration settings for the batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get worker processing configuration",
                "responses": {
                    "200": {
                        "description": "Processing configuration retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Update the configuration settings for the batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Update worker processing configuration",
                "parameters": [
                    {
                        "description": "New processing configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/worker.ProcessingConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processing configuration updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid configuration data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Cannot update config while processor is running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/detailed-status": {
            "get": {
                "description": "Get comprehensive status information including tracker details and configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get detailed worker status",
                "responses": {
                    "200": {
                        "description": "Detailed status retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/export": {
            "get": {
                "description": "Export processing results in JSON or CSV format with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Export processing results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Export format (json, csv)",
                        "name": "format",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by result status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Results exported successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/pause": {
            "post": {
                "description": "Pause the currently running batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Pause batch processing worker",
                "responses": {
                    "200": {
                        "description": "Batch processing paused successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Processor not running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/progress": {
            "get": {
                "description": "Get detailed progress information about the current batch processing operation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get worker processing progress",
                "responses": {
                    "200": {
                        "description": "Processing progress retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/results": {
            "get": {
                "description": "Get processing results with optional filtering by status and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get worker processing results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by result status (pending, processing, success, failed, skipped, completed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processing results retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/results/clear": {
            "post": {
                "description": "Clear all processing results and reset statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Clear processing results",
                "responses": {
                    "200": {
                        "description": "Results cleared successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Cannot clear results while processor is running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/results/time-range": {
            "get": {
                "description": "Get processing results within a specific time range with optional status filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get results by time range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 format)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 format)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by result status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Time range results retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid time format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/resume": {
            "post": {
                "description": "Resume the paused batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Resume batch processing worker",
                "responses": {
                    "200": {
                        "description": "Batch processing resumed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Processor already running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/shutdown": {
            "post": {
                "description": "Perform a graceful shutdown with cleanup and final checkpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Graceful shutdown",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shutdown timeout in seconds (default: 300)",
                        "name": "timeout",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Graceful shutdown completed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/start": {
            "post": {
                "description": "Start the batch processing worker with optional configuration overrides",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Start batch processing worker",
                "parameters": [
                    {
                        "description": "Optional processing configuration overrides",
                        "name": "config",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/worker.ProcessingConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Batch processing started successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Processor already running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/stats": {
            "get": {
                "description": "Get detailed statistics about the batch processing operations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get worker processing statistics",
                "responses": {
                    "200": {
                        "description": "Processing statistics retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/status": {
            "get": {
                "description": "Get the current status of the batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get worker processing status",
                "responses": {
                    "200": {
                        "description": "Processing status retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/stop": {
            "post": {
                "description": "Stop the currently running batch processing worker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Stop batch processing worker",
                "responses": {
                    "200": {
                        "description": "Batch processing stopped successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - Processor not running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/subscription-external/worker/summary": {
            "get": {
                "description": "Get a summary of the current processing run with rates and timing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get processing summary",
                "responses": {
                    "200": {
                        "description": "Processing summary retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/userbase/upload": {
            "post": {
                "description": "Upload and process CSV or XLSX files containing user base data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserBase"
                ],
                "summary": "Upload user base file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV or XLSX file containing user data",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully processed records",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid file format or failed to retrieve file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to parse file or store records",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service is healthy and running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Get Prometheus metrics for the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Metrics endpoint",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.BackfillRequest": {
            "type": "object",
            "properties": {
                "end_index": {
                    "type": "integer"
                },
                "entry_channel": {
                    "description": "Single channel (legacy support)",
                    "type": "string"
                },
                "entry_channels": {
                    "description": "Multiple channels for rotation",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msisdns": {
                    "description": "optional explicit list to include",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start_index": {
                    "description": "0 or -1 means use full list",
                    "type": "integer"
                },
                "telco": {
                    "type": "string"
                }
            }
        },
        "domain.BatchOptinRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "entry_channel": {
                    "type": "string"
                },
                "msisdns": {
                    "description": "if provided, skip generation",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "telco": {
                    "type": "string"
                }
            }
        },
        "domain.ChargeRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "pricepointId": {
                    "type": "integer"
                },
                "productId": {
                    "type": "integer"
                },
                "shortCode": {
                    "type": "string"
                }
            }
        },
        "domain.ChargeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "inError": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "responseData": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "domain.EnhancedBackfillRequest": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "description": "Enhanced features",
                    "type": "string"
                },
                "batch_size": {
                    "type": "integer"
                },
                "checkpoint_interval": {
                    "type": "integer"
                },
                "dry_run": {
                    "type": "boolean"
                },
                "end_index": {
                    "type": "integer"
                },
                "entry_channel": {
                    "type": "string"
                },
                "entry_channels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "force_reprocess": {
                    "type": "boolean"
                },
                "max_workers": {
                    "type": "integer"
                },
                "msisdns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rate_limit_per_second": {
                    "type": "integer"
                },
                "start_index": {
                    "type": "integer"
                },
                "telco": {
                    "description": "Basic fields from original BackfillRequest",
                    "type": "string"
                },
                "use_charging_failures": {
                    "type": "boolean"
                }
            }
        },
        "domain.GetStatusRequest": {
            "type": "object",
            "properties": {
                "clientIp": {
                    "type": "string"
                },
                "controlKeyword": {
                    "type": "string"
                },
                "controlServiceKeyword": {
                    "type": "string"
                },
                "entryChannel": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "subId": {
                    "type": "integer"
                },
                "userIdentifier": {
                    "type": "string"
                },
                "userIdentifierType": {
                    "type": "string"
                }
            }
        },
        "domain.MTResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "inError": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "responseData": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "domain.OptinRequest": {
            "type": "object",
            "properties": {
                "entry_channel": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "telco": {
                    "type": "string"
                }
            }
        },
        "domain.PriorityRetryQueue": {
            "description": "Manages failed opt-ins that require immediate retry with exponential backoff",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_attempt_at": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "next_retry_at": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RenewalCycle": {
            "description": "Tracks each step of the opt-out/opt-in renewal process",
            "type": "object",
            "properties": {
                "billing_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "cycle_number": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "msisdn": {
                    "type": "string"
                },
                "opt_in_response": {
                    "type": "string"
                },
                "opt_in_status": {
                    "type": "string"
                },
                "opt_in_time": {
                    "type": "string"
                },
                "opt_out_response": {
                    "type": "string"
                },
                "opt_out_status": {
                    "type": "string"
                },
                "opt_out_time": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "subscription_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RenewalMetrics": {
            "description": "Performance metrics for the renewal system",
            "type": "object",
            "properties": {
                "average_cycle_time": {
                    "type": "number"
                },
                "churned_subscriptions": {
                    "type": "integer"
                },
                "failed_renewals": {
                    "type": "integer"
                },
                "last_run_time": {
                    "type": "string"
                },
                "success_rate": {
                    "type": "number"
                },
                "successful_renewals": {
                    "type": "integer"
                },
                "total_processed": {
                    "type": "integer"
                }
            }
        },
        "domain.RenewalResponse": {
            "description": "Response structure for renewal operations",
            "type": "object",
            "properties": {
                "billing_status": {
                    "type": "string"
                },
                "cycle_id": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "opt_in_status": {
                    "type": "string"
                },
                "opt_out_status": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.SubscriptionConfirmationRequest": {
            "type": "object",
            "properties": {
                "clientIp": {
                    "type": "string"
                },
                "entryChannel": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "transactionAuthCode": {
                    "type": "string"
                },
                "userIdentifier": {
                    "type": "string"
                },
                "userIdentifierType": {
                    "type": "string"
                }
            }
        },
        "domain.SubscriptionWithRenewalInfo": {
            "type": "object",
            "properties": {
                "campaignUrl": {
                    "type": "string"
                },
                "cancelReason": {
                    "type": "string"
                },
                "cancelSource": {
                    "type": "string"
                },
                "clientIp": {
                    "type": "string"
                },
                "consecutive_payment_failures": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "entryChannel": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "largeAccount": {
                    "type": "string"
                },
                "last_renewal_attempt": {
                    "type": "string"
                },
                "last_successful_payment": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "partnerRoleId": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "renewal_status": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subKeyword": {
                    "type": "string"
                },
                "total_renewal_attempts": {
                    "type": "integer"
                },
                "trackingId": {
                    "type": "string"
                },
                "transactionAuthCode": {
                    "type": "string"
                },
                "userIdentifier": {
                    "type": "string"
                },
                "userIdentifierType": {
                    "type": "string"
                }
            }
        },
        "domain.UnsubscriptionRequest": {
            "type": "object",
            "properties": {
                "cancelReason": {
                    "type": "integer"
                },
                "cancelSource": {
                    "type": "integer"
                },
                "clientIp": {
                    "type": "string"
                },
                "controlKeyword": {
                    "type": "string"
                },
                "controlServiceKeyword": {
                    "type": "string"
                },
                "entryChannel": {
                    "type": "string"
                },
                "largeAccount": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "subId": {
                    "type": "integer"
                },
                "subKeyword": {
                    "type": "string"
                },
                "trackingId": {
                    "type": "string"
                },
                "userIdentifier": {
                    "type": "string"
                },
                "userIdentifierType": {
                    "type": "string"
                }
            }
        },
        "handler.ChurnEvaluationResponse": {
            "description": "Result of a churn evaluation operation",
            "type": "object",
            "properties": {
                "churned": {
                    "description": "Number of subscriptions churned",
                    "type": "integer",
                    "example": 25
                },
                "message": {
                    "description": "Result message",
                    "type": "string",
                    "example": "Churn evaluation completed"
                },
                "processed": {
                    "description": "Number of subscriptions processed",
                    "type": "integer",
                    "example": 150
                },
                "renewed": {
                    "description": "Number of subscriptions renewed",
                    "type": "integer",
                    "example": 125
                },
                "status": {
                    "description": "Operation status",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.ManualRenewalRequest": {
            "description": "Request structure for manual renewal",
            "type": "object",
            "required": [
                "msisdn",
                "product_id"
            ],
            "properties": {
                "channel": {
                    "description": "Entry channel",
                    "type": "string",
                    "example": "API"
                },
                "msisdn": {
                    "description": "Mobile number",
                    "type": "string",
                    "example": "1234567890"
                },
                "product_id": {
                    "description": "Product identifier",
                    "type": "string",
                    "example": "PROD_001"
                }
            }
        },
        "handler.RenewalHealthResponse": {
            "description": "Health status of the renewal system",
            "type": "object",
            "properties": {
                "timestamp": {
                    "description": "Health check timestamp",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "worker_health": {
                    "description": "Worker health details",
                    "type": "object",
                    "additionalProperties": true
                },
                "worker_running": {
                    "description": "Worker status",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.RenewalWorkerStatus": {
            "description": "Status and metrics of the renewal worker",
            "type": "object",
            "properties": {
                "metrics": {
                    "description": "Worker metrics",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RenewalMetrics"
                        }
                    ]
                },
                "running": {
                    "description": "Whether the worker is running",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.partnerMtRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "largeAccount": {
                    "type": "string"
                },
                "mcc": {
                    "type": "string"
                },
                "mnc": {
                    "type": "string"
                },
                "moTransactionUUID": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "pricepointId": {
                    "type": "integer"
                },
                "priority": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "sendDate": {
                    "type": "string"
                },
                "text": {
                    "description": "Not used by current upstream optin API, accepted for compatibility",
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "monitoring.AlertThresholds": {
            "type": "object",
            "properties": {
                "database_errors": {
                    "description": "Alert if \u003e 10 in 1 hour",
                    "type": "integer"
                },
                "high_failure_rate": {
                    "description": "Alert if \u003e 80%",
                    "type": "number"
                },
                "high_queue_size": {
                    "description": "Alert if \u003e 10000",
                    "type": "integer"
                },
                "low_success_rate": {
                    "description": "Alert if \u003c 60%",
                    "type": "number"
                },
                "processing_delay": {
                    "description": "Alert if \u003e 5 minutes",
                    "type": "number"
                },
                "service_unavailable": {
                    "description": "Alert if service down",
                    "type": "boolean"
                }
            }
        },
        "worker.ProcessingConfig": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "TIMWE Subscription External Service API",
	Description:      "|",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
